name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::892386869854:role/GRANO-PROPERTIES
          aws-region: us-east-1

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: aws s3 sync ./dist s3://granoproperties.com --delete

      - name: Invalidate
        run: aws cloudfront create-invalidation \
          --distribution-id EPS8DMVSGPO8C \
          --paths "/*"
